name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '56 * * * *'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-json:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.run.outputs.CHANGED }}
      frontend: ${{ steps.changes.outputs.frontend }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - uses: dorny/paths-filter@v3
      id: changes
      with:
        base: HEAD
        filters: |
          frontend:
            - 'frontend/**'

    # Cache versions.json so it doesn't update the site if there are no changes
    - name: versions.json cache
      uses: actions/cache@v4
      env:
        cache-name: cache-versions-json
      with:
        path: "rke2-versions.json"
        key: ${{ env.cache-name }}-${{ hashFiles('**/rke2-versions.json') }}
        restore-keys: ${{ env.cache-name }}-

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Invalidate versions.json cache if frontend changed
      if: steps.changes.outputs.frontend == 'true'
      run: |
        rm -f rke2-versions.json

    - name: Run rke2-versions
      id: run
      run: |
        pip install -r requirements.txt
        python rke2-versions.py | tee "${GITHUB_OUTPUT}"

    - name: Upload artifacts
      if: steps.run.outputs.CHANGED == 'true'
      uses: actions/upload-artifact@v4
      with:
        path: data/
        name: rke2-versions

  # Deployment job
  build-ui:
    if: |
      needs.build-json.outputs.CHANGED == 'true' ||
      needs.build-json.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    needs: build-json
    permissions:
      pages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download json from build-json job
        uses: actions/download-artifact@v5
        with:
          name: rke2-versions
          path: data/

      - name: Copy the json file to the static gatsby folder
        run: |
          mkdir -p ./frontend/static/
          cp ./data/rke2.json ./frontend/static/
          ls ./frontend/static/

      - name: Deploy to GitHub Pages
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: x-access-token:${{ secrets.GITHUB_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
          working-dir: "./frontend"
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com
